### ISSUE TITLE
Error importing any games to Steam library and constant 'Steam is running' notifications

### ISSUE THREAD

**Issue by Vladg24YT** [SteamGridDB/steamgriddb-manager#91] opened 2020-07-13 09:47 UTC
**Describe the bug**
I tried to import *The Escapists 2* from Epic Games Launcher to Steam, but after several attempts to import, `Microsoft Visual C++ Runtime Library` error appeared. Also the manager kept saying that Steam was running, but in both default Win7 task manager and Process Hacker 2 there were no executables from Steam directory running.

**To Reproduce**
1. Go to `Import Games` tab
2. Click on **Import** or **Import All** button twice
3. A notification that Steam is running appears
4. Click on **Import** or **Import All** button about twenty times
5. First `Microsoft Visual C++ Runtime Library` error pops out
6. Click **Skip (Пропустить)**
7. Second `Microsoft Visual C++ Runtime Library` error pops out

**Expected behavior**
*The Escapists 2* imported into Steam.

**Operating System**
 - Windows 7 Maximum x64 Service Pack 1

**Installed Launchers**
- Epic Games Launcher
- Uplay
- Origin
- Steam

**Screenshots**
![First error](https://user-images.githubusercontent.com/35247077/87288828-87605580-c504-11ea-8178-3bd927f260f4.png)
![Second error](https://user-images.githubusercontent.com/35247077/87288867-9941f880-c504-11ea-888b-3c3c082c8456.png)

**Log**
[log.log](https://github.com/SteamGridDB/steamgriddb-manager/files/4911632/log.log)

**Additional context**
I tried running as administrator and in compatability mode with Windows 7. It didn't help. Also, the second Visual C++ error pops up even if I make manager's window active or `Alt+Tab` back to it.

**Comment by thepiratex2** [comment] 2020-07-13 10:00
same with me bro

**Comment by Vladg24YT** [comment] 2020-07-14 19:43
**Update**
*The Escapists 2* was imported into my Steam library as a Non-Steam Game. I just had to re-launch Steam client.

The error and notifications still pop up when importing other games, though.

**Comment by RobTheRealLifeAnimoo** [comment] 2020-07-22 08:16
Duplicate of #63 - same issue here too

**Comment by RobTheRealLifeAnimoo** [comment] 2020-07-22 08:17
#63 looks really similar to issue here

**Comment by WanHaes** [comment] 2020-07-25 13:17
Very same issue.

**Comment by aranel616** [comment] 2021-01-06 09:49
Unfortunately, we do not support Windows 7, as Microsoft ended support for Windows 7 on January 14, 2020. If anybody can reproduce this issue on a later version of Windows, please open a new issue.

**Closed by aranel616** 2021-01-06 09:49 UTC
Labels: invalid
