### ISSUE TITLE
Rocket League no Images

### ISSUE THREAD

**Issue by epicsucks** [SteamGridDB/steamgriddb-manager#97] opened 2020-10-02 16:11 UTC
I just started using steam grid db. It works Great for steam input, however for rocket league imported from epic games, there are no pictures I cannot find a way to add my own, including looking in the directory of the app.

To reproduce:
open steam grid db import rocket league from epic games.
Click on it in your library. click hero or capsule or horizontal capsule.
you get infinite loading with nothing ever happening.

This is works fine with all other steam games in the manager and have not tried any other epic games.

-thank you

**Comment by sam97** [comment] 2020-12-05 22:12
This is happening because Rocket League is still tagged as a Steam game in SteamGridDB, while your local copy is from Epic Games Store. Either SGDB has to create an entry for RL under EGS or SGDBManager should have a fallback mechanism to do a full search for games that are not found.

For now, I managed to work around this by opening the console and putting appropriate breakpoints in `Search.jsx` and `SGDB.js` to change `options.type` from `"egs"` to `"steam"` and `options.id` from `"Sugar"` to `"252950"`, which are the respective IDs for Steam and its Rocket League game. It's a little too technical so I cannot write it all out.

**Comment by epicsucks** [comment] 2020-12-06 02:30
thank you for responding, I fixed the issue by just setting the images in
steam itself. I do have experience with the cli  but I have no idea why it
would help me with editing files. Or is this a different built in console
in your program? would I find these files in the install directory of steam
grid db manager? At this point it's just academic as I have found a much
easier way to do it.

**Comment by sam97** [comment] 2020-12-06 08:34
SGDB has fixed this issue. Find our conversation here: https://discord.com/channels/488621078302949377/552548093703487510/784908541785538560.

The CLI is the Console tab in Chrome dev tool. You can open it by pressing Ctrl+Shift+i in the app.

~Sam
________________________________

**Comment by epicsucks** [comment] 2020-12-06 12:51
Oh! so it runs in chrome frame.....

**Comment by epicsucks** [comment] 2020-12-06 12:53
when I heard console I thought you meant bash/cmd/powershell

**Comment by aranel616** [comment] 2021-01-08 21:34
I have confirmed that this issue is fixed due to backend changes in the SGDB api. Closing.

**Closed by aranel616** 2021-01-08 21:34 UTC
Labels: bug
